content = """
Aldığın soruya aşağıdaki metne göre cevaplar ver, mümkün olduğunca metnin dışına çıkma.

<<<HAKKIMDAKİ METİN
        Kişisel Bilgiler
Adım Mehmet Büyükgümüş, 28.10.1994 İstanbul doğumluyum. Evliyim. Paris'te yaşıyorum. Bana her zaman "mehmetbgumus@gmail.com" adresinden ulaşabilirsiniz.
        Eğitim bilgileri
    2008 yılında Lise eğitimimi İstanbul Prof. Dr. Mümtaz Turhan Sosyal Bilimler Lisesi'nde tamamladım. Lise eğitimimin içerisinde 
uluslararası bakalorya programı (IB (International Baccalaureate)'dan da aynı zamanda mezun oldum. Bu program kapsamında üniversite eğitimine yakın içeriklerde matematik, edebiyat, tarih, sosyoloji, çoğrafya, biyoloji ve bilgi felsefesi (theory of knowledge) dersleri aldım. Bu derslerin içeriklerinin yanı sıra yaptığım ödevler de beni oldukça geliştirdi. Örneğin edebiyat derslerinde tiyatro ve romanlar üzerine makaleler yazıp tartışmalar organize ettim. Matematik dersinde portfolyolar oluşturdum. Biyoloji derslerinde ise deneyler yaptım. Bu birbirinden farklı disiplinler beni daha analitik düşünebilin ve farklı disiplerin içerdikleri bilgiler ve yöntemlerle farklı disiplinlerde çalışabilme yeteneğine kavuşturdu. IB programı kapsamında eğitim dili İngilizce olduğu için İngilizcemi de epey ilerletmiş oldum. Profesyonel düzeyde metinler yazabilir ve sunumlar yapabilir oldum.
    2013 Lisans eğitimini İstanbul Ticaret Üniversitesi Muhasebe ve Denetim bölümünde tamamladım. Bu alanda saygın ve hatta 
Türkiye'de muhasebe mesleğinin kuruluş kanununu hazırlayan önemli hocalardan dersler aldım. Genel anlamda yüksel lisans ve hatta doktora düzeyinde verilen dersler lisans bölümüm oldukça spesifik bir alanda olduğu için lisans düzeyinde veriliyordu. Örneğin uluslararası finansal raporlama standartları, denetim, hile denetimi, dış ticaret muhasebesi gibi derin ve teknik konularla henüz lisans düzeyindeyken bilgi sahibi oldum. Lisans sürecimde İstanbul Ticaret Odası'nda, Nar Denetim Mali Müşavirlik LTD. İBB'ye ait Metro A.Ş'de uzun dönemli stajlar yaptım.
    2019 yılında İstanbul Bahçeşehir Üniversitesi'nde yüksek lisans eğitimine başladım ve "Borsa Istanbul investments by fundamental analysis: An application in the forest products and furniture sector" başlıklı tezimle 2022 yılında tamamladım.
(https://tez.yok.gov.tr/UlusalTezMerkezi/tezSorguSonucYeni.jsp). Tez konumunda Borsa İstanbul yatırımlarında orman sektöründe faaliyet gösteren iki şirketin yatırım yapılabilirlik durumunu temel analiz yöntemi kullanarak değerlendirdim. Bu çalışma boyunca Türkiye'de Kamuyu Aydınlatma Platformu(KAP)'unda yer alan verilerden faydalandım.
        Çalışma Hayatı
    2018 yılında lisans mezuniyetimin ardından bağımsız denetim sektöründe global bir bağımsız denetim şirketi olan Mazars'da 
junior olarak çalışmaya başladım. Buradaki çalışma hayatım boyunca senior auditorlüğe kadar yükseldim ve denetim alanında ekip yönetme tecrübesi edindim. Şirketlerin finansal tablolarına ilişkin denetim raporlarını hazırladım ve hatta bunların bazıların bir bölümü borsada halka açık şirketlerdi. Şirketlerin bilanço, gelir tablosu, nakit akış tablolarını ayrı ayrı denetimlerini ve raporlamalarını yaptım. Çalıştığım şirket Fransa merkezli olduğu için Türkiye'de yatırımları bulunan bir çok Fransız şirketinin de denetim çalışmalarında bulundum.
        Paris dönemi
    2022 yılında Paris'e taşındım. Paris'e taşındığımda daha önce hiç fransızca bilmiyordum. Cours de Civilisation Sorbonne'da 
Fransızca öğrenmeye başladım. Bir buçuk yıl içerisinde B2 seviyesinde Fransızca öğrendim. Bu süreç içerisinde bir yandan Fransa'yı tanımaya ve Fransız kültürüne adapte olmaya çalışırken veri bilimi alanında çalışmalarıma başladım. Şu dönemde veri bilimi ve bağımsız denetim alanında iş arayışım devam etmektedir.
    Daha önceki çalışma hayatımda finansal verileri çokça kullandığım için veriye yabancı biri değilim. Ancak verilerden anlamlı 
bilgiler çıkarma konusunda yalnızca Excel kullanıyordum. Veri bilimi projelerinde ise Python'la çalışabilmek için öncelikle Python öğrenmeye başladım. Bu süreçte Python'un temel operasyonlarını, veri bilimi ve veri görselleştirme için gerekli Pandas, Numpy, Matplotlib, Seaborn gibi kütüphaneleriöğrerendim. Ardından bu alanda derinleşebilmek adına CRM Analytics, Reccomendation Systems, Feature Engineering ve Machine Learning konularında çalışmalar yaptım. Bu yaptığım çalışmalar protföyümde yer almaktadır.
>>>
"""